// Generated by CoffeeScript 1.6.3
(function() {
  var MWS_PRODUCTS, ProductsClient, enums, mws, requests, types,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  mws = require('./core');

  MWS_PRODUCTS = new mws.Service({
    name: "Products",
    group: "Products",
    path: "/Products/2011-10-01",
    version: "2011-10-01",
    legacy: false
  });

  enums = {
    ItemCondition: (function(_super) {
      __extends(_Class, _super);

      function _Class() {
        _Class.__super__.constructor.call(this, 'ItemCondition', ['New', 'Used', 'Collectible', 'Refurbished', 'Club']);
      }

      return _Class;

    })(mws.Enum)
  };

  types = {
    ServiceStatus: mws.types.ServiceStatus,
    MarketplaceId: {
      ATVPDKIKX0DER: 'amazon.com',
      A1F83G8C2ARO7P: 'amazon.co.uk',
      A13V1IB3VIYZZH: 'amazon.fr',
      A1PA6795UKMFR9: 'amazon.de',
      APJ6JRA9NG5V4: 'amazon.it',
      A1RKKUPIHCS9HS: 'amazon.es'
    }
  };

  requests = {
    GetServiceStatus: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetServiceStatus', [], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    ListMatchingProducts: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'ListMatchingProducts', [new mws.Param('MarketplaceId', 'Id', true), new mws.Param('Query', true), new mws.Param('QueryContextId', false)], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetMatchingProduct: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetMatchingProduct', [new mws.Param('MarketplaceId', true), new mws.ParamList('ASINList', 'ASIN')], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetMatchingProductForId: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetMatchingProductForId', [new mws.Param('MarketplaceId', true), new mws.Param('IdType', true), new mws.ParamList('IdList', 'Id')], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetCompetitivePricingForSKU: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetCompetitivePricingForSKU', [new mws.Param('MarketplaceId', 'Id', true), new mws.ParamList('SellerSKUList', 'SellerSKU', true)], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetCompetitivePricingForASIN: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetCompetitivePricingForASIN', [new mws.Param('MarketplaceId', 'Id', true), new mws.ParamList('ASINList', 'ASIN')], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetLowestOfferListingsForSKU: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetLowestOfferListingsForSKU', [new mws.Param('MarketplaceId', 'Id', true), new mws.ParamList('SellerSKUList', 'SellerSKU', true), new enums.ItemCondition('ItemCondition')], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetLowestOfferListingsForASIN: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetLowestOfferListingsForASIN', [new mws.Param('MarketplaceId', 'Id', true), new enums.ItemCondition('ItemCondition'), new mws.ParamList('ASINList', 'ASIN')], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetMyPriceForSKU: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetMyPriceForSKU', [new mws.Param('MarketplaceId', 'Id', true), new mws.ParamList('SellerSKUList', 'SellerSKU', true), new enums.ItemCondition('ItemCondition')], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetMyPriceForASIN: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetMyPriceForASIN', [new mws.Param('MarketplaceId', 'Id', true), new enums.ItemCondition('ItemCondition'), new mws.ParamList('ASINList', 'ASIN')], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetProductCategoriesForSKU: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetProductCategoriesForSKU', [new mws.Param('MarketplaceId', 'Id', true), new mws.Param('SellerSKU', true)], {}, null, init);
      }

      return _Class;

    })(mws.Request),
    GetProductCategoriesForASIN: (function(_super) {
      __extends(_Class, _super);

      function _Class(init) {
        _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetProductCategoriesForASIN', [new mws.Param('MarketplaceId', 'Id', true), new mws.Param('ASIN', true)], {}, null, init);
      }

      return _Class;

    })(mws.Request)
  };

  ProductsClient = (function(_super) {
    __extends(ProductsClient, _super);

    function ProductsClient() {
      ProductsClient.__super__.constructor.apply(this, arguments);
    }

    ProductsClient.prototype.getServiceStatus = function(cb) {
      var _this = this;
      return this.invoke(new requests.GetServiceStatus(), {}, function(res) {
        var status, _ref, _ref1;
        status = (_ref = (_ref1 = res.result) != null ? _ref1.Status : void 0) != null ? _ref : null;
        return cb(status, res);
      });
    };

    ProductsClient.prototype.listMatchingProducts = function(query, context, cb) {
      var req,
        _this = this;
      req = new requests.ListMatchingProducts({
        MarketplaceId: this.marketplaceId,
        Query: query,
        QueryContextId: context != null ? context : void 0
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getMatchingProduct = function(asins, cb) {
      var req,
        _this = this;
      req = new requests.GetMatchingProduct({
        MarketplaceId: this.marketplaceId,
        ASINList: asins != null ? asins : []
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getMatchingProductForId = function(idType, ids, cb) {
      var req,
        _this = this;
      req = new requests.GetMatchingProductForId({
        MarketplaceId: this.marketplaceId,
        IdType: idType,
        IdList: ids
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getCompetitivePricingForSKU = function(skus, cb) {
      var req,
        _this = this;
      req = new requests.GetCompetitivePricingForSKU({
        MarketplaceId: this.marketplaceId,
        SellerSKUList: skus != null ? skus : []
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getCompetitivePricingForASIN = function(asins, cb) {
      var req,
        _this = this;
      req = new requests.GetCompetitivePricingForASIN({
        MarketplaceId: this.marketplaceId,
        ASINList: asins != null ? asins : []
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getLowestOfferListingsForSKU = function(skus, condition, cb) {
      var req,
        _this = this;
      req = new requests.GetLowestOfferListingsForSKU({
        MarketplaceId: this.marketplaceId,
        SellerSKUList: skus != null ? skus : [],
        ItemCondition: condition != null ? condition : void 0
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getLowestOfferListingsForASIN = function(asins, condition, cb) {
      var req,
        _this = this;
      req = new requests.GetLowestOfferListingsForASIN({
        MarketplaceId: this.marketplaceId,
        ASINList: asins != null ? asins : [],
        ItemCondition: condition != null ? condition : void 0
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getMyPriceForSKU = function(skus, condition, cb) {
      var req,
        _this = this;
      req = new requests.GetMyPriceForSKU({
        MarketplaceId: this.marketplaceId,
        SellerSKUList: skus != null ? skus : [],
        ItemCondition: condition != null ? condition : void 0
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getMyPriceForASIN = function(asins, condition, cb) {
      var req,
        _this = this;
      req = new requests.GetMyPriceForASIN({
        MarketplaceId: this.marketplaceId,
        ASINList: asins != null ? asins : [],
        ItemCondition: condition != null ? condition : void 0
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getProductCategoriesForSKU = function(sku, cb) {
      var req,
        _this = this;
      req = new requests.GetProductCategoriesForSKU({
        MarketplaceId: this.marketplaceId,
        SellerSKU: sku
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    ProductsClient.prototype.getProductCategoriesForASIN = function(asin, cb) {
      var req,
        _this = this;
      req = new requests.GetProductCategoriesForASIN({
        MarketplaceId: this.marketplaceId,
        ASIN: asin
      });
      return this.invoke(req, {}, function(res) {
        return cb(res);
      });
    };

    return ProductsClient;

  })(mws.Client);

  module.exports = {
    service: MWS_PRODUCTS,
    enums: enums,
    requests: requests,
    Client: ProductsClient
  };

}).call(this);
