// Generated by CoffeeScript 1.3.3
var MWS_PRODUCTS, ProductsClient, enums, mws, requests, types,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

mws = require('./core');

MWS_PRODUCTS = new mws.Service({
  name: "Products",
  group: "Products",
  path: "/Products/2011-10-01",
  version: "2011-10-01",
  legacy: false
});

enums = {
  ItemCondition: (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      _Class.__super__.constructor.call(this, 'ItemCondition', ['New', 'Used', 'Collectible', 'Refurbished', 'Club']);
    }

    return _Class;

  })(mws.Enum)
};

types = {
  ServiceStatus: mws.types.ServiceStatus,
  MarketplaceId: {
    ATVPDKIKX0DER: 'amazon.com',
    A1F83G8C2ARO7P: 'amazon.co.uk',
    A13V1IB3VIYZZH: 'amazon.fr',
    A1PA6795UKMFR9: 'amazon.de',
    APJ6JRA9NG5V4: 'amazon.it',
    A1RKKUPIHCS9HS: 'amazon.es'
  }
};

requests = {
  GetServiceStatus: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetServiceStatus', [], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  ListMatchingProducts: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'ListMatchingProducts', [new mws.ParamList('MarketplaceId', 'Id', true), new mws.Param('Query', true), new mws.Param('QueryContextId', false)], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  GetMatchingProduct: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetMatchingProduct', [new mws.ParamList('MarketplaceId', 'Id', true), new mws.ParamList('ASINList', 'ASIN')], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  GetCompetitivePricingForSKU: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetCompetitivePricingForSKU', [new mws.ParamList('MarketplaceId', 'Id', true), new mws.ParamList('SellerSKUList', 'SellerSKU', true)], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  GetCompetitivePricingForASIN: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetCompetitivePricingForASIN', [new mws.ParamList('MarketplaceId', 'Id', true), new mws.ParamList('ASINList', 'ASIN')], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  GetLowestOfferListingsForSKU: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetLowestOfferListingsForSKU', [new mws.ParamList('MarketplaceId', 'Id', true), new mws.ParamList('SellerSKUList', 'SellerSKU', true), new enums.ItemCondition('ItemCondition')], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  GetLowestOfferListingsForASIN: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetLowestOfferListingsForASIN', [new mws.ParamList('MarketplaceId', 'Id', true), new enums.ItemCondition('ItemCondition'), new mws.ParamList('ASINList', 'ASIN')], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  GetProductCategoriesForSKU: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetProductCategoriesForSKU', [new mws.ParamList('MarketplaceId', 'Id', true), new mws.Param('SellerSKU', true)], {}, null, init);
    }

    return _Class;

  })(mws.Request),
  GetProductCategoriesForASIN: (function(_super) {

    __extends(_Class, _super);

    function _Class(init) {
      _Class.__super__.constructor.call(this, MWS_PRODUCTS, 'GetProductCategoriesForASIN', [new mws.ParamList('MarketplaceId', 'Id', true), new mws.Param('ASIN', true)], {}, null, init);
    }

    return _Class;

  })(mws.Request)
};

ProductsClient = (function(_super) {

  __extends(ProductsClient, _super);

  function ProductsClient() {
    ProductsClient.__super__.constructor.apply(this, arguments);
    this.marketplaceIds = this.marketplaceId ? [this.marketplaceId] : [];
  }

  ProductsClient.prototype.setMarketplaces = function() {
    var marketplaceIds;
    marketplaceIds = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this.marketplaceIds = marketplaceIds;
  };

  ProductsClient.prototype.getServiceStatus = function(cb) {
    var _this = this;
    return this.invoke(new requests.GetServiceStatus(), {}, function(res) {
      var status, _ref, _ref1;
      status = (_ref = (_ref1 = res.result) != null ? _ref1.Status : void 0) != null ? _ref : null;
      return cb(status, res);
    });
  };

  ProductsClient.prototype.listMatchingProducts = function() {
    var cb, context, marketplaceIds, query, req, _i, _ref,
      _this = this;
    query = arguments[0], context = arguments[1], marketplaceIds = 4 <= arguments.length ? __slice.call(arguments, 2, _i = arguments.length - 1) : (_i = 2, []), cb = arguments[_i++];
    req = new requests.ListMatchingProducts({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      Query: query,
      QueryContextId: context != null ? context : void 0
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  ProductsClient.prototype.getMatchingProduct = function() {
    var asins, cb, marketplaceIds, req, _i, _ref,
      _this = this;
    asins = arguments[0], marketplaceIds = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), cb = arguments[_i++];
    req = new requests.GetMatchingProduct({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      ASINList: asins != null ? asins : []
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  ProductsClient.prototype.getCompetitivePricingForSKU = function() {
    var cb, marketplaceIds, req, skus, _i, _ref,
      _this = this;
    skus = arguments[0], marketplaceIds = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), cb = arguments[_i++];
    req = new requests.GetCompetitivePricingForSKU({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      SellerSKUList: skus != null ? skus : []
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  ProductsClient.prototype.getCompetitivePricingForASIN = function() {
    var asins, cb, marketplaceIds, req, _i, _ref,
      _this = this;
    asins = arguments[0], marketplaceIds = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), cb = arguments[_i++];
    req = new requests.GetCompetitivePricingForASIN({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      ASINList: asins != null ? asins : []
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  ProductsClient.prototype.getLowestOfferListingsForSKU = function() {
    var cb, condition, marketplaceIds, req, skus, _i, _ref,
      _this = this;
    skus = arguments[0], condition = arguments[1], marketplaceIds = 4 <= arguments.length ? __slice.call(arguments, 2, _i = arguments.length - 1) : (_i = 2, []), cb = arguments[_i++];
    req = new requests.GetLowestOfferListingsForSKU({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      SellerSKUList: skus != null ? skus : [],
      ItemCondition: condition != null ? condition : void 0
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  ProductsClient.prototype.getLowestOfferListingsForASIN = function() {
    var asins, cb, condition, marketplaceIds, req, _i, _ref,
      _this = this;
    asins = arguments[0], condition = arguments[1], marketplaceIds = 4 <= arguments.length ? __slice.call(arguments, 2, _i = arguments.length - 1) : (_i = 2, []), cb = arguments[_i++];
    req = new requests.GetLowestOfferListingsForASIN({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      ASINList: asins != null ? asins : [],
      ItemCondition: condition != null ? condition : void 0
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  ProductsClient.prototype.getProductCategoriesForSKU = function() {
    var cb, marketplaceIds, req, sku, _i, _ref,
      _this = this;
    sku = arguments[0], marketplaceIds = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), cb = arguments[_i++];
    req = new requests.GetProductCategoriesForSKU({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      SellerSKU: sku
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  ProductsClient.prototype.getProductCategoriesForASIN = function() {
    var asin, cb, marketplaceIds, req, _i, _ref,
      _this = this;
    asin = arguments[0], marketplaceIds = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), cb = arguments[_i++];
    req = new requests.GetProductCategoriesForASIN({
      MarketplaceId: (_ref = marketplaceIds != null ? marketplaceIds : this.marketplaceIds) != null ? _ref : this.marketplaceId,
      ASIN: asin
    });
    return this.invoke(req, {}, function(res) {
      return cb(res);
    });
  };

  return ProductsClient;

})(mws.Client);

module.exports = {
  service: MWS_PRODUCTS,
  enums: enums,
  requests: requests,
  Client: ProductsClient
};
